### ISSUE TITLE
Exception when adding daily note.

### ISSUE THREAD

**Issue by iogf** [iogf/mnem#1]
[tau@sigma ~]$ mnem -a 'Look at upwork for a job' -d -m 2
Traceback (most recent call last):
  File "/usr/bin/mnem", line 77, in <module>
    main()
  File "/usr/bin/mnem", line 73, in main
    args.cmd(args)
  File "/usr/bin/mnem", line 57, in <lambda>
    args.minutes if args.minutes else xrange(1, 60)), 
  File "/usr/lib/python2.7/site-packages/mnemcore.py", line 23, in add
    time = datetime(*map(int, ind))
ValueError: day is out of range for month

**Comment by iogf** [comment]
Possible fix using calendar package.
